### ISSUE TITLE
Nether DIM Switch

### ISSUE THREAD

**Issue by kylemcqueen75** [Flaxbeard/Flaxbeards-Steam-Power#224]
Hello!

I have recently been building a modpack and have been using "Steamcraft 0.27.5." Everything was working great, but recently I started having an issue with the Nether moving to DIM0 (the same as the overworld) I decided to test each one of my mods to find the issue, as there is 0 console log error. I got to this mod Flaxbeard'sSteamPower-1.7.10-0.28.2.jar. Now the nether loads to DIM-1 but after going to the nether it changes to DIM0. I used CoFHCore to see what dim it was loading.

**Comment by kylemcqueen75** [comment]
It wasn't clear but after updating to the newest Flaxbeard'sSteamPower-1.7.10-0.28.2.jar, I started having this DIM issue.

**Comment by xbony2** [comment]
Wut :? Does the nether generate in the surface? I'm kind of confused.

**Comment by kylemcqueen75** [comment]
The nether portal will not take you to DIM-1, it takes you to another DIM0 that looks like the nether except it generates over world ores and buildings. Its basicly the nether "renamed" to the wrong DIM. I will record a YouTube video and post it here later on


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: xbony2 <notifications@github.com> </div><div>Date:03/06/2015  4:40 PM  (GMT-06:00) </div><div>To: Flaxbeard/Flaxbeards-Steam-Power <Flaxbeards-Steam-Power@noreply.github.com> </div><div>Cc: kylemcqueen75 <kylemcqueen75@hotmail.com> </div><div>Subject: Re: [Flaxbeards-Steam-Power] Nether DIM Switch (#224) </div><div>
</div>
Wut :? Does the nether generate in the surface? I'm kind of confused.

---

**Comment by elifoster** [comment]
I don't understand how this could ever happen.

**Comment by ate0ate** [comment]
I too am having extreme problems with the nether. For me, things look normal upon entering at first but soon certain sounds stop playing, such as player block/item pick up and all mob noises. I can still hear blocks breaking however. The real problem comes like thirty seconds after the sounds stop. ALL blocks appear to unload chunk by chunk and my player drops through the world like what happens sometimes normally at first when entering a new dimension. There's no crash or anything but the nether is completely unplayable. Exiting the world and reloading works temporarily but then in under a minute the whole world vanishes. Its definitely a pretty bad bug that messes up gameplay entirely if you rely on anything nether related. I use a ton of mods and it took me quite a few hours to narrow the problem down to the latest FSP update. Screwed up my single player world pretty badly:(

**Comment by elifoster** [comment]
What's strange is that @fc47cc7 is the only world-related thing that has changed lately, and I can't see why it would affect this. I'll look into it when I get a chance.

**Comment by Monstrel** [comment]
Looking at the changes in src/main/java/flaxbeard/steamcraft/world/SteamcraftOreGen.java with that commit, it looks like the new extra dimension copper and zinc ore generation code might be flawed.

In lines 19-23, I don't believe the zincIDs and copperIDs arrays are being populated correctly.  They are initialized to the length of the number of dimensions in the dimension list, but never populated.  Then those arrays are iterated and calls to generateExtra() are made, passing the value in the array as a dimensionID, which would be 0 for each element in the initialized array.  Then, in line 107 world.provider.dimensionId = id; which sets it to 0.

I have no experience working with worldgen, and I may not understand what's really supposed to be going on there, but if I'm right about what that array code is doing, it may not be what is intended.

**Comment by elifoster** [comment]
Here's a StackOverflow that should sort of explain what goes on here http://stackoverflow.com/questions/7781038/convert-a-string-of-numbers-into-an-array

And even if the code there was flawed, it wouldn't make sense for simple oregen to change the entire worldgen scheme.

**Comment by Monstrel** [comment]
I understand what the intention is, but the code doesn't do that.  zincArray is initialized and assigned from splitting the string, then int[] zincIDs is initialized based on zincArray.length.  zincArray is not referenced again and zincIDs is never populated so all the values therein remain 0.

What I don't know anything about is the ramification of setting world.provider.dimensionId = 0 in that context.

Sorry if any of this is a red herring; I'm just going down the rabbit hole from your link to the probably relevant commit, and that bit looked like it wasn't doing what seemed to be intended.

**Comment by elifoster** [comment]
I suppose a fix to that particular issue would be just a check if there even any values in the config option

**Comment by UndeadZeratul** [comment]
That won't matter, you're pulling in the array of strings into zincArray, then making a new array of integers, zincIDs, with nothing inside it.  You need to convert each slot in the string array into an integer and place it into the second array in order for it to work correctly.  If the array is empty, nothing breaks because there's nothing in the arrays anyways, and no invalid code is run.

Try something like:
```
String[] zincArray = Config.zincDims.split(";");
final int[] zincIDs = new int[zincArray.length];
for(int i = 0; i < zincArray.length; n++) {
   zincIDs[i] = Integer.parseInt(zincArray[i]);
}
```

**Comment by Monstrel** [comment]
Splitting an empty string returns 1 element, so even if the extra dimensions config is empty, generateExtra() is called twice for each call to generate(), as both zincIDs and copperIDs will be single element arrays whose element value is 0.

Semantically, when generating for the Overworld, Nether and End in the switch statement, you read the value of world.provider.dimensionId and act according to which dimension is appropriate.

In any case, when generateExtra() is called, it sets world.provider.dimensionId to 0.  I question whether that is valid or if that pollutes the state.  This is where my knowledge of java exceeds my knowledge of minecraft modding.  Does that world object remain to be reused in subsequent calls to generate()?  If so, the next call to generate() would cause the switch to select the overworld generation, and any other use of that property could be broken, which might explain why ghast sounds near a player in the nether are heard by players in the overworld instead in SMP.

To follow UndeadZeratul's comment, once zincIDs and copperIDs are validated to be in a correct state, I'd suggest something like this:

`
        for (int id : copperIDs) {
            if (id == world.provider.dimensionid) {
                generateExtra(world, random, chunkX * 16, chunkZ * 16);
            }
        }
`
Which would be consistent with the method used to call generation in the standard dimensions.  The id parameter and value assignment to world.provider.dimensionid could then be factored out of generateExtra().

I'd probably also try to create a unified list of extra dimensions to generate in so that the copper and zinc generation wasn't called twice for each extra dimension, or refactor generateExtra() into a pair of functions like generateExtraCopper() and generateExtraZinc().

**Comment by elifoster** [comment]
That makes sense. I will work on something for this when I get a chance.

**Comment by OreCruncher** [comment]
I have this problem, and updated to 28.3 and now it crashes.  Here is a snip:

	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at flaxbeard.steamcraft.world.SteamcraftOreGen.generate(SteamcraftOreGen.java:26)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at fastcraft.a.c.a(F:84)
	at fastcraft.Hooks.r(F:139)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)

**Comment by lehjr** [comment]
Just a thought, but wouldn't an empty array would give you an empty string at array[0]? I'm pretty sure you don't want to feed an empty string to Integer.parseInt(), since that seems to be the source of the current crash.

**Comment by lehjr** [comment]
Regarding commit c475856f4eee2b8877cb4de39ebe4903c960b8f6 and the new error: 

String[] zincArray = Config.zincDims.split(";");
final int[] zincIDs = new int[zincArray.length];
for(int i = 0; i < zincArray.length; n++) {
   zincIDs[i] = Integer.parseInt(zincArray[i]);
}

If the config setting is blank for that, the array will have a single element with a blank string, and passing a blank string to  Integer.parseInt() will throw a NumberFormatException.

**Comment by elifoster** [comment]
Yeah I didn't think of that, and my config had a value that I forgot about when I tested. I mean, hey, this is why it's beta.

**Comment by UndeadZeratul** [comment]
I think it's called "Early Access" nowadays.

**Comment by lehjr** [comment]
Meh, all software is beta at best. Look at MS Windows. 

Anyway, on a test build, I replaced:

zincIDs[i] = Integer.parseInt(zincArray[i]);

with
 
zincIDs[i] = zincArray[i].isEmpty() ? 0:Integer.parseInt(zincArray[i]);

and the same for the copper setup. I don't know if "0" is a good default value, but at least it isn't crashing.

**Comment by elifoster** [comment]
0 will not be a default value. 0, 1, and -1 should never be in that config, and it, if uncommented, will report errors frequently about that.
